include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = SDL2HelloWorld
SDL2HelloWorld_OBJC_FILES = \
	SDLWindow.m \
	SDLRenderer.m \
	TextRenderer.m \
	HelloWorldApp.m \
	sdl_main.m

SDL2HelloWorld_OBJCFLAGS = -fobjc-arc
SDL2HelloWorld_CPPFLAGS = -I/usr/include/SDL2 -I/mingw64/include/SDL2
ifeq ($(findstring mingw,$(GNUSTEP_TARGET_OS)),mingw)
    SDL2HelloWorld_LDFLAGS = -lSDL2main -lSDL2 -lSDL2_ttf
else
    SDL2HelloWorld_LDFLAGS = -lSDL2 -lSDL2_ttf
endif

include $(GNUSTEP_MAKEFILES)/tool.make