name: Build Objective-C on macOS
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Check Xcode version and install SDL2
        run: |
          xcodebuild -version
          clang --version
          
          # Install SDL2 and SDL2_ttf via Homebrew
          brew install sdl2 sdl2_ttf
      
      - name: Build Hello World
        run: |
          # Compile using native macOS Objective-C runtime
          clang -framework Foundation hello.m -o hello
          
          echo "=== Checking executable ==="
          file hello
          ls -la hello
      
      - name: Run Hello World
        run: |
          echo "=== Running hello application ==="
          ./hello
      
      - name: Test with Xcode project
        run: |
          # Create a simple Xcode project structure
          mkdir -p HelloWorldApp
          cd HelloWorldApp
          
          # Copy shared source files
          cp ../hello.h .
          cp ../hello.m .
          
          # Build with clang directly
          clang -framework Foundation hello.m -o HelloWorldApp
          
          echo "=== Running HelloWorldApp ==="
          ./HelloWorldApp
      
      - name: Create Package
        run: |
          mkdir -p package
          
          # Copy executables
          cp hello package/
          if [ -f HelloWorldApp/HelloWorldApp ]; then
              cp HelloWorldApp/HelloWorldApp package/HelloWorldApp
          fi
          
          # Create a shell script to run the app
          cat << 'EOF' > package/run-hello.sh
          #!/bin/bash
          echo "Running Objective-C Hello World on macOS..."
          ./hello
          echo "Done!"
          EOF
          chmod +x package/run-hello.sh
          
          # Create README
          cat << 'EOF' > package/README.txt
          Objective-C Hello World for macOS
          ==================================
          
          This package contains a simple Objective-C application built with native macOS Foundation framework.
          
          Files:
          - hello: Built with clang and Foundation framework
          - HelloWorldApp: Alternative build from subdirectory
          - run-hello.sh: Shell script to run the demo
          
          Requirements:
          - macOS (uses native Foundation framework)
          
          To run:
          ./hello
          or
          ./run-hello.sh
          EOF
          
          echo "=== Package contents ==="
          ls -la package/
          
          echo "=== Testing packaged executable ==="
          cd package
          ./hello && echo "✓ Packaged executable works!" || echo "✗ Packaged executable failed"
      
      - name: Build SDL2 Hello World
        run: |
          echo "=== Building SDL2 Hello World for macOS ==="
          
          # Get SDL2 paths from Homebrew
          SDL2_PATH=$(brew --prefix sdl2)
          SDL2_TTF_PATH=$(brew --prefix sdl2_ttf)
          
          echo "SDL2 path: $SDL2_PATH"
          echo "SDL2_ttf path: $SDL2_TTF_PATH"
          
          # Build SDL2 Hello World
          clang -framework Foundation \
                -I"$SDL2_PATH/include" \
                -I"$SDL2_TTF_PATH/include" \
                -L"$SDL2_PATH/lib" \
                -L"$SDL2_TTF_PATH/lib" \
                SDLWindow.m SDLRenderer.m TextRenderer.m HelloWorldApp.m sdl_main.m \
                -o sdl_hello \
                -lSDL2 -lSDL2_ttf
          
          echo "=== Checking SDL2 executable ==="
          file sdl_hello
          ls -la sdl_hello
          otool -L sdl_hello
          
          echo "=== SDL2 Hello World built successfully ==="
          echo "Note: GUI application requires display - would need virtual display for testing"
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: objc-hello-world-macos
          path: package/