name: Build GNUstep / SDL2HelloWorld (Windows)

on:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      #-------------------------------------------------------------
      # 1.  Checkout the repository
      #-------------------------------------------------------------
      - uses: actions/checkout@v3

      #-------------------------------------------------------------
      # 2.  MSYS2 environment with Clang, libobjc2, GNUstep, SDL2
      #-------------------------------------------------------------
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          release: false          # always grab the latest MSYS2
          update: true
          install: >-
            mingw-w64-x86_64-clang
            mingw-w64-x86_64-lld
            mingw-w64-x86_64-libobjc2
            mingw-w64-x86_64-gnustep-base
            mingw-w64-x86_64-gnustep-make
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-SDL2_ttf
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-pkgconf

      #-------------------------------------------------------------
      # 3.  Configure & build with Clang and lld
      #-------------------------------------------------------------
      - name: Configure & Build
        shell: msys2 {0}
        run: |
          # Make a fresh build directory
          cmake -S . -B build -G "Unix Makefiles" \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_COMPILER=clang \
                -DCMAKE_CXX_COMPILER=clang++ \
                -DCMAKE_OBJC_COMPILER=clang \
                -DCMAKE_OBJC_FLAGS="-fobjc-arc -fobjc-runtime=gnustep-2.1" \
                -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld"
          cmake --build build --parallel

      #-------------------------------------------------------------
      # 4.  Smoke-test and archive the artefact
      #-------------------------------------------------------------
      - name: Check executable
        shell: msys2 {0}
        run: |
          file build/SDL2HelloWorld.exe
          ls -lh build/SDL2HelloWorld.exe

      - uses: actions/upload-artifact@v4
        with:
          name: SDL2HelloWorld-windows
          path: build/SDL2HelloWorld.exe
