name: Build GNUstep on Linux
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CC: clang
      CXX: clang++
      LD: ld.lld
      LDFLAGS: -fuse-ld=lld
    steps:
      - uses: actions/checkout@v3
      
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang \
            lld \
            git \
            cmake \
            make \
            pkg-config \
            libffi-dev \
            libicu-dev \
            libxml2-dev \
            libxslt1-dev \
            libssl-dev \
            libgnutls28-dev \
            libavahi-client-dev \
            libblocksruntime-dev \
            libkqueue-dev \
            libpthread-workqueue-dev \
            libjpeg-dev \
            libtiff-dev \
            libpng-dev \
            libcups2-dev \
            libfreetype6-dev \
            libcairo2-dev \
            libxt-dev \
            libgl1-mesa-dev \
            libsdl2-dev \
            libsdl2-ttf-dev
      
      - name: Build and install libobjc2
        run: |
          git clone --recurse-submodules --branch v2.2.1 https://github.com/gnustep/libobjc2
          cd libobjc2
          mkdir build && cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_INSTALL_PREFIX=/usr
          make -j$(nproc)
          sudo make install
          sudo ldconfig
      
      - name: Build and install GNUstep Make
        run: |
          git clone --branch make-2_9_3 https://github.com/gnustep/tools-make
          cd tools-make
          ./configure \
            --prefix=/usr \
            --with-config-file=/usr/etc/GNUstep.conf \
            --with-layout=fhs \
            --enable-native-objc-exceptions \
            --enable-objc-arc \
            --enable-install-ld-so-conf \
            CC=clang \
            CXX=clang++ \
            LDFLAGS="-fuse-ld=lld"
          make -j$(nproc)
          sudo make install
          # Source GNUstep environment
          . /usr/share/GNUstep/Makefiles/GNUstep.sh
          echo "GNUSTEP_MAKEFILES=$GNUSTEP_MAKEFILES" >> $GITHUB_ENV
      
      - name: Build and install GNUstep Base
        run: |
          . /usr/share/GNUstep/Makefiles/GNUstep.sh
          git clone --branch base-1_30_0 https://github.com/gnustep/libs-base
          cd libs-base
          ./configure \
            --disable-iconv \
            --disable-tls \
            CC=clang \
            CXX=clang++ \
            LDFLAGS="-fuse-ld=lld"
          make -j$(nproc)
          sudo make install
          sudo ldconfig
      
      - name: Test Hello World
        run: |
          . /usr/share/GNUstep/Makefiles/GNUstep.sh
          
          # Compile and run the shared hello.m
          clang `gnustep-config --objc-flags` hello.m -o hello `gnustep-config --base-libs`
          ./hello
      
      - name: Test with GNUmakefile
        run: |
          . /usr/share/GNUstep/Makefiles/GNUstep.sh
          
          # Create a simple project with GNUmakefile using shared files
          mkdir -p TestApp
          cd TestApp
          
          # Copy shared source files
          cp ../hello.h .
          cp ../hello.m .
          
          cat << 'EOF' > GNUmakefile
          include $(GNUSTEP_MAKEFILES)/common.make
          
          TOOL_NAME = HelloApp
          HelloApp_OBJC_FILES = hello.m
          HelloApp_OBJCFLAGS = -fobjc-arc
          
          include $(GNUSTEP_MAKEFILES)/tool.make
          EOF
          
          make
          ./obj/HelloApp
      
      - name: Test SDL2 Hello World
        run: |
          . /usr/share/GNUstep/Makefiles/GNUstep.sh
          
          # Build SDL2 Hello World with direct compilation
          echo "=== Building SDL2 Hello World with clang ==="
          clang `gnustep-config --objc-flags` \
                -I/usr/include/SDL2 \
                SDLWindow.m SDLRenderer.m TextRenderer.m HelloWorldApp.m sdl_main.m \
                -o sdl_hello \
                `gnustep-config --base-libs` \
                -lSDL2 -lSDL2_ttf
          
          echo "=== Checking SDL2 executable ==="
          file sdl_hello
          ls -la sdl_hello
          
          echo "=== SDL2 Hello World built successfully ==="
          echo "Note: GUI application requires display - would run in headless environment"
          
          # Test with GNUmakefile
          echo "=== Building with GNUmakefile ==="
          cp GNUmakefile.sdl GNUmakefile
          make clean
          make
          
          echo "=== SDL2 GNUmakefile build complete ==="
          ls -la obj/SDL2HelloWorld
